ALTER TABLE "Course" ADD COLUMN "cover" TEXT;
ALTER TABLE "Course" ADD COLUMN "category" TEXT;
ALTER TABLE "Course" ADD COLUMN "language" TEXT;
ALTER TABLE "Course" ADD COLUMN "difficulty" TEXT;
ALTER TABLE "Course" ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Course" ADD COLUMN "price" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'CNY';
ALTER TABLE "Course" ADD COLUMN "versionLabel" TEXT;
ALTER TABLE "Course" ADD COLUMN "unlockScope" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Course" ADD COLUMN "isPurchased" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Course" ADD COLUMN "isLearnable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Course" ADD COLUMN "isOffline" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Course" ADD COLUMN "supportedLanguages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Course" ADD COLUMN "chapterCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "lessonCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "taskCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Chapter" ADD COLUMN "summary" TEXT;

ALTER TABLE "Lesson" ADD COLUMN "durationMinutes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Task" ADD COLUMN "type" TEXT;
ALTER TABLE "Task" ADD COLUMN "points" INTEGER NOT NULL DEFAULT 0;
