export const courseSeedData = [
    {
        id: "course-frontend-foundation",
        slug: "frontend-foundation",
        title: "前端工程基础课包",
        summary: "覆盖工程化、组件化、状态管理和常见页面开发流程。",
        cover: "/images/courses/frontend-foundation.png",
        category: "frontend",
        language: "zh-CN",
        difficulty: "beginner",
        tags: ["基础", "工程化", "Web"],
        price: "199.00",
        currency: "CNY",
        status: "published",
        version: 13,
        versionLabel: "v1.3.0",
        unlockScope: "full",
        isPurchased: true,
        isLearnable: true,
        isOffline: false,
        supportedLanguages: ["zh-CN", "en-GB"],
        chapterCount: 2,
        lessonCount: 6,
        taskCount: 4,
        createdAt: "2026-07-01T09:00:00.000Z",
        updatedAt: "2026-08-01T09:00:00.000Z",
    },
    {
        id: "course-api-design",
        slug: "api-design",
        title: "API 设计与后端契约课包",
        summary: "聚焦接口建模、状态字段、分页返回与前后端协作。",
        cover: "/images/courses/api-design.png",
        category: "backend",
        language: "zh-CN",
        difficulty: "intermediate",
        tags: ["API", "契约", "NestJS"],
        price: "299.00",
        currency: "CNY",
        status: "published",
        version: 21,
        versionLabel: "v2.1.0",
        unlockScope: "preview",
        isPurchased: false,
        isLearnable: false,
        isOffline: false,
        supportedLanguages: ["zh-CN", "en-GB"],
        chapterCount: 3,
        lessonCount: 8,
        taskCount: 6,
        createdAt: "2026-06-15T09:00:00.000Z",
        updatedAt: "2026-08-02T09:00:00.000Z",
    },
    {
        id: "course-creative-workflows",
        slug: "creative-workflows",
        title: "内容制作与创作流程课包",
        summary: "适合内容生产、项目协作和交付流程的系统化训练。",
        cover: "/images/courses/creative-workflows.png",
        category: "productivity",
        language: "zh-CN",
        difficulty: "advanced",
        tags: ["内容", "流程", "协作"],
        price: "399.00",
        currency: "CNY",
        status: "archived",
        version: 10,
        versionLabel: "v1.0.0",
        unlockScope: "none",
        isPurchased: false,
        isLearnable: false,
        isOffline: false,
        supportedLanguages: ["zh-CN", "en-GB"],
        chapterCount: 2,
        lessonCount: 5,
        taskCount: 3,
        createdAt: "2026-05-12T09:00:00.000Z",
        updatedAt: "2026-06-01T09:00:00.000Z",
    },
] as const;

export const chapterSeedData = [
    {
        id: "chapter-frontend-1",
        courseId: "course-frontend-foundation",
        title: "工程基础",
        summary: "认识项目结构、工具链和核心规范。",
        sortOrder: 0,
        status: "published",
        createdAt: "2026-07-01T09:00:00.000Z",
        updatedAt: "2026-08-01T09:00:00.000Z",
    },
    {
        id: "chapter-frontend-2",
        courseId: "course-frontend-foundation",
        title: "页面交付",
        summary: "围绕页面开发、状态流与交互收尾。",
        sortOrder: 1,
        status: "published",
        createdAt: "2026-07-01T09:10:00.000Z",
        updatedAt: "2026-08-01T09:10:00.000Z",
    },
    {
        id: "chapter-api-1",
        courseId: "course-api-design",
        title: "领域划分",
        summary: "从资源和职责开始组织接口。",
        sortOrder: 0,
        status: "published",
        createdAt: "2026-06-15T09:00:00.000Z",
        updatedAt: "2026-08-02T09:00:00.000Z",
    },
    {
        id: "chapter-api-2",
        courseId: "course-api-design",
        title: "查询契约",
        summary: "统一分页、过滤和状态返回。",
        sortOrder: 1,
        status: "published",
        createdAt: "2026-06-15T09:10:00.000Z",
        updatedAt: "2026-08-02T09:10:00.000Z",
    },
    {
        id: "chapter-api-3",
        courseId: "course-api-design",
        title: "联调落地",
        summary: "处理边界、错误码和兼容策略。",
        sortOrder: 2,
        status: "published",
        createdAt: "2026-06-15T09:20:00.000Z",
        updatedAt: "2026-08-02T09:20:00.000Z",
    },
    {
        id: "chapter-creative-1",
        courseId: "course-creative-workflows",
        title: "流程总览",
        summary: "理解内容生产和交付的基础路径。",
        sortOrder: 0,
        status: "archived",
        createdAt: "2026-05-12T09:00:00.000Z",
        updatedAt: "2026-06-01T09:00:00.000Z",
    },
] as const;

export const lessonSeedData = [
    {
        id: "lesson-frontend-1",
        courseId: "course-frontend-foundation",
        chapterId: "chapter-frontend-1",
        title: "项目骨架",
        summary: "建立目录结构与基础约定。",
        durationMinutes: 20,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-07-01T09:00:00.000Z",
        updatedAt: "2026-08-01T09:00:00.000Z",
    },
    {
        id: "lesson-frontend-2",
        courseId: "course-frontend-foundation",
        chapterId: "chapter-frontend-1",
        title: "组件系统",
        summary: "封装常用布局与交互组件。",
        durationMinutes: 35,
        sortOrder: 1,
        status: "published",
        createdAt: "2026-07-01T09:05:00.000Z",
        updatedAt: "2026-08-01T09:05:00.000Z",
    },
    {
        id: "lesson-frontend-3",
        courseId: "course-frontend-foundation",
        chapterId: "chapter-frontend-2",
        title: "状态管理",
        summary: "处理页面状态与数据流。",
        durationMinutes: 28,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-07-01T09:10:00.000Z",
        updatedAt: "2026-08-01T09:10:00.000Z",
    },
    {
        id: "lesson-api-1",
        courseId: "course-api-design",
        chapterId: "chapter-api-1",
        title: "资源与边界",
        summary: "识别核心资源和职责边界。",
        durationMinutes: 24,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-06-15T09:00:00.000Z",
        updatedAt: "2026-08-02T09:00:00.000Z",
    },
    {
        id: "lesson-api-2",
        courseId: "course-api-design",
        chapterId: "chapter-api-1",
        title: "分页与筛选",
        summary: "定义通用查询参数和返回格式。",
        durationMinutes: 30,
        sortOrder: 1,
        status: "published",
        createdAt: "2026-06-15T09:05:00.000Z",
        updatedAt: "2026-08-02T09:05:00.000Z",
    },
    {
        id: "lesson-api-3",
        courseId: "course-api-design",
        chapterId: "chapter-api-2",
        title: "状态与契约",
        summary: "统一响应结构与状态表达。",
        durationMinutes: 26,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-06-15T09:10:00.000Z",
        updatedAt: "2026-08-02T09:10:00.000Z",
    },
    {
        id: "lesson-creative-1",
        courseId: "course-creative-workflows",
        chapterId: "chapter-creative-1",
        title: "内容工作流",
        summary: "认识素材、产出和交付节奏。",
        durationMinutes: 18,
        sortOrder: 0,
        status: "archived",
        createdAt: "2026-05-12T09:00:00.000Z",
        updatedAt: "2026-06-01T09:00:00.000Z",
    },
] as const;

export const taskSeedData = [
    {
        id: "task-frontend-1",
        courseId: "course-frontend-foundation",
        lessonId: "lesson-frontend-1",
        title: "创建 Web 项目骨架",
        description: null,
        type: "implementation",
        points: 10,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-07-01T09:00:00.000Z",
        updatedAt: "2026-08-01T09:00:00.000Z",
    },
    {
        id: "task-frontend-2",
        courseId: "course-frontend-foundation",
        lessonId: "lesson-frontend-2",
        title: "实现通用组件",
        description: null,
        type: "implementation",
        points: 20,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-07-01T09:05:00.000Z",
        updatedAt: "2026-08-01T09:05:00.000Z",
    },
    {
        id: "task-api-1",
        courseId: "course-api-design",
        lessonId: "lesson-api-1",
        title: "梳理资源边界",
        description: null,
        type: "analysis",
        points: 12,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-06-15T09:00:00.000Z",
        updatedAt: "2026-08-02T09:00:00.000Z",
    },
    {
        id: "task-api-2",
        courseId: "course-api-design",
        lessonId: "lesson-api-2",
        title: "统一查询协议",
        description: null,
        type: "analysis",
        points: 18,
        sortOrder: 0,
        status: "published",
        createdAt: "2026-06-15T09:05:00.000Z",
        updatedAt: "2026-08-02T09:05:00.000Z",
    },
    {
        id: "task-creative-1",
        courseId: "course-creative-workflows",
        lessonId: "lesson-creative-1",
        title: "整理交付步骤",
        description: null,
        type: "analysis",
        points: 8,
        sortOrder: 0,
        status: "archived",
        createdAt: "2026-05-12T09:00:00.000Z",
        updatedAt: "2026-06-01T09:00:00.000Z",
    },
] as const;

export const contentAssetSeedData = [
    {
        id: "asset-frontend-1",
        courseId: "course-frontend-foundation",
        lessonId: "lesson-frontend-1",
        taskId: "task-frontend-1",
        fileName: "项目骨架参考图.png",
        mimeType: "image/png",
        url: "/images/courses/frontend-foundation.png",
        metadata: {
            title: "项目骨架参考图",
            type: "image",
            version: "1.0.0",
            sizeLabel: "1.2 MB",
            status: "published",
        },
        createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
        id: "asset-frontend-2",
        courseId: "course-frontend-foundation",
        lessonId: "lesson-frontend-2",
        taskId: "task-frontend-2",
        fileName: "通用组件清单.pdf",
        mimeType: "application/pdf",
        url: "/files/courses/frontend-components.pdf",
        metadata: {
            title: "通用组件清单",
            type: "document",
            version: "1.1.0",
            sizeLabel: "180 KB",
            status: "published",
        },
        createdAt: "2026-07-01T09:05:00.000Z",
    },
    {
        id: "asset-api-1",
        courseId: "course-api-design",
        lessonId: "lesson-api-1",
        taskId: "task-api-1",
        fileName: "资源分层说明.pdf",
        mimeType: "application/pdf",
        url: "/files/courses/api-resource-map.pdf",
        metadata: {
            title: "资源分层说明",
            type: "document",
            version: "1.0.0",
            sizeLabel: "96 KB",
            status: "published",
        },
        createdAt: "2026-06-15T09:00:00.000Z",
    },
    {
        id: "asset-api-2",
        courseId: "course-api-design",
        lessonId: "lesson-api-2",
        taskId: "task-api-2",
        fileName: "查询协议示例.pdf",
        mimeType: "application/pdf",
        url: "/files/courses/api-query-contract.pdf",
        metadata: {
            title: "查询协议示例",
            type: "document",
            version: "1.0.1",
            sizeLabel: "112 KB",
            status: "published",
        },
        createdAt: "2026-06-15T09:05:00.000Z",
    },
    {
        id: "asset-creative-1",
        courseId: "course-creative-workflows",
        lessonId: "lesson-creative-1",
        taskId: "task-creative-1",
        fileName: "交付流程示意.png",
        mimeType: "image/png",
        url: "/files/courses/creative-workflows-flow.png",
        metadata: {
            title: "交付流程示意",
            type: "image",
            version: "1.0.0",
            sizeLabel: "840 KB",
            status: "archived",
        },
        createdAt: "2026-05-12T09:00:00.000Z",
    },
] as const;
