/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppRouteImport } from "./routes/app";
import { Route as AppIndexRouteImport } from "./routes/app/index";
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AppAccountIndexRouteImport } from "./routes/app/account/index";
import { Route as AppAccountMembershipRouteImport } from "./routes/app/account/membership";
import { Route as AppAccountNotificationsRouteImport } from "./routes/app/account/notifications";
import { Route as AppAccountOrdersRouteImport } from "./routes/app/account/orders";
import { Route as AppAccountProfileRouteImport } from "./routes/app/account/profile";
import { Route as AppAccountSecurityRouteImport } from "./routes/app/account/security";
import { Route as AppAccountSessionsRouteImport } from "./routes/app/account/sessions";
import { Route as AppAdminIndexRouteImport } from "./routes/app/admin/index";
import { Route as AppAdminContentRouteImport } from "./routes/app/admin/content";
import { Route as AppAdminLicensesRouteImport } from "./routes/app/admin/licenses";
import { Route as AppAdminSystemRouteImport } from "./routes/app/admin/system";
import { Route as AppAdminUsersRouteImport } from "./routes/app/admin/users";
import { Route as AppContentIndexRouteImport } from "./routes/app/content/index";
import { Route as AppContentLibraryRouteImport } from "./routes/app/content/library";
import { Route as AppContentPackagesRouteImport } from "./routes/app/content/packages";
import { Route as AppContentPublishingRouteImport } from "./routes/app/content/publishing";
import { Route as AppContentReviewRouteImport } from "./routes/app/content/review";
import { Route as AppLearningIndexRouteImport } from "./routes/app/learning/index";
import { Route as AppLearningCoursesRouteImport } from "./routes/app/learning/courses";
import { Route as AppLearningProgressRouteImport } from "./routes/app/learning/progress";
import { Route as AppSettingsIndexRouteImport } from "./routes/app/settings/index";
import { Route as AppSettingsGeneralRouteImport } from "./routes/app/settings/general";
import { Route as AppSettingsPreferencesRouteImport } from "./routes/app/settings/preferences";
import { Route as AppContentPackagesNewRouteImport } from "./routes/app/content/packages/new";

const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
    id: "/app",
    path: "/app",
    getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => AppRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
    id: "/auth/forgot-password",
    path: "/auth/forgot-password",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
    id: "/auth/login",
    path: "/auth/login",
    getParentRoute: () => rootRouteImport,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
    id: "/auth/signup",
    path: "/auth/signup",
    getParentRoute: () => rootRouteImport,
} as any);
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
    id: "/account/",
    path: "/account/",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountMembershipRoute = AppAccountMembershipRouteImport.update({
    id: "/account/membership",
    path: "/account/membership",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
    id: "/account/notifications",
    path: "/account/notifications",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountOrdersRoute = AppAccountOrdersRouteImport.update({
    id: "/account/orders",
    path: "/account/orders",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
    id: "/account/profile",
    path: "/account/profile",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
    id: "/account/security",
    path: "/account/security",
    getParentRoute: () => AppRoute,
} as any);
const AppAccountSessionsRoute = AppAccountSessionsRouteImport.update({
    id: "/account/sessions",
    path: "/account/sessions",
    getParentRoute: () => AppRoute,
} as any);
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
    id: "/admin/",
    path: "/admin/",
    getParentRoute: () => AppRoute,
} as any);
const AppAdminContentRoute = AppAdminContentRouteImport.update({
    id: "/admin/content",
    path: "/admin/content",
    getParentRoute: () => AppRoute,
} as any);
const AppAdminLicensesRoute = AppAdminLicensesRouteImport.update({
    id: "/admin/licenses",
    path: "/admin/licenses",
    getParentRoute: () => AppRoute,
} as any);
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
    id: "/admin/system",
    path: "/admin/system",
    getParentRoute: () => AppRoute,
} as any);
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
    id: "/admin/users",
    path: "/admin/users",
    getParentRoute: () => AppRoute,
} as any);
const AppContentIndexRoute = AppContentIndexRouteImport.update({
    id: "/content/",
    path: "/content/",
    getParentRoute: () => AppRoute,
} as any);
const AppContentLibraryRoute = AppContentLibraryRouteImport.update({
    id: "/content/library",
    path: "/content/library",
    getParentRoute: () => AppRoute,
} as any);
const AppContentPackagesRoute = AppContentPackagesRouteImport.update({
    id: "/content/packages",
    path: "/content/packages",
    getParentRoute: () => AppRoute,
} as any);
const AppContentPublishingRoute = AppContentPublishingRouteImport.update({
    id: "/content/publishing",
    path: "/content/publishing",
    getParentRoute: () => AppRoute,
} as any);
const AppContentReviewRoute = AppContentReviewRouteImport.update({
    id: "/content/review",
    path: "/content/review",
    getParentRoute: () => AppRoute,
} as any);
const AppLearningIndexRoute = AppLearningIndexRouteImport.update({
    id: "/learning/",
    path: "/learning/",
    getParentRoute: () => AppRoute,
} as any);
const AppLearningCoursesRoute = AppLearningCoursesRouteImport.update({
    id: "/learning/courses",
    path: "/learning/courses",
    getParentRoute: () => AppRoute,
} as any);
const AppLearningProgressRoute = AppLearningProgressRouteImport.update({
    id: "/learning/progress",
    path: "/learning/progress",
    getParentRoute: () => AppRoute,
} as any);
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AppRoute,
} as any);
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
    id: "/settings/general",
    path: "/settings/general",
    getParentRoute: () => AppRoute,
} as any);
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
    id: "/settings/preferences",
    path: "/settings/preferences",
    getParentRoute: () => AppRoute,
} as any);
const AppContentPackagesNewRoute = AppContentPackagesNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => AppContentPackagesRoute,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/app": typeof AppRouteWithChildren;
    "/app/dashboard": typeof AppDashboardRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/login": typeof AuthLoginRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/app/": typeof AppIndexRoute;
    "/app/account/membership": typeof AppAccountMembershipRoute;
    "/app/account/notifications": typeof AppAccountNotificationsRoute;
    "/app/account/orders": typeof AppAccountOrdersRoute;
    "/app/account/profile": typeof AppAccountProfileRoute;
    "/app/account/security": typeof AppAccountSecurityRoute;
    "/app/account/sessions": typeof AppAccountSessionsRoute;
    "/app/admin/content": typeof AppAdminContentRoute;
    "/app/admin/licenses": typeof AppAdminLicensesRoute;
    "/app/admin/system": typeof AppAdminSystemRoute;
    "/app/admin/users": typeof AppAdminUsersRoute;
    "/app/content/library": typeof AppContentLibraryRoute;
    "/app/content/packages": typeof AppContentPackagesRouteWithChildren;
    "/app/content/publishing": typeof AppContentPublishingRoute;
    "/app/content/review": typeof AppContentReviewRoute;
    "/app/learning/courses": typeof AppLearningCoursesRoute;
    "/app/learning/progress": typeof AppLearningProgressRoute;
    "/app/settings/general": typeof AppSettingsGeneralRoute;
    "/app/settings/preferences": typeof AppSettingsPreferencesRoute;
    "/app/account/": typeof AppAccountIndexRoute;
    "/app/admin/": typeof AppAdminIndexRoute;
    "/app/content/": typeof AppContentIndexRoute;
    "/app/learning/": typeof AppLearningIndexRoute;
    "/app/settings/": typeof AppSettingsIndexRoute;
    "/app/content/packages/new": typeof AppContentPackagesNewRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/app/dashboard": typeof AppDashboardRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/login": typeof AuthLoginRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/app": typeof AppIndexRoute;
    "/app/account/membership": typeof AppAccountMembershipRoute;
    "/app/account/notifications": typeof AppAccountNotificationsRoute;
    "/app/account/orders": typeof AppAccountOrdersRoute;
    "/app/account/profile": typeof AppAccountProfileRoute;
    "/app/account/security": typeof AppAccountSecurityRoute;
    "/app/account/sessions": typeof AppAccountSessionsRoute;
    "/app/admin/content": typeof AppAdminContentRoute;
    "/app/admin/licenses": typeof AppAdminLicensesRoute;
    "/app/admin/system": typeof AppAdminSystemRoute;
    "/app/admin/users": typeof AppAdminUsersRoute;
    "/app/content/library": typeof AppContentLibraryRoute;
    "/app/content/packages": typeof AppContentPackagesRouteWithChildren;
    "/app/content/publishing": typeof AppContentPublishingRoute;
    "/app/content/review": typeof AppContentReviewRoute;
    "/app/learning/courses": typeof AppLearningCoursesRoute;
    "/app/learning/progress": typeof AppLearningProgressRoute;
    "/app/settings/general": typeof AppSettingsGeneralRoute;
    "/app/settings/preferences": typeof AppSettingsPreferencesRoute;
    "/app/account": typeof AppAccountIndexRoute;
    "/app/admin": typeof AppAdminIndexRoute;
    "/app/content": typeof AppContentIndexRoute;
    "/app/learning": typeof AppLearningIndexRoute;
    "/app/settings": typeof AppSettingsIndexRoute;
    "/app/content/packages/new": typeof AppContentPackagesNewRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/app": typeof AppRouteWithChildren;
    "/app/dashboard": typeof AppDashboardRoute;
    "/auth/forgot-password": typeof AuthForgotPasswordRoute;
    "/auth/login": typeof AuthLoginRoute;
    "/auth/signup": typeof AuthSignupRoute;
    "/app/": typeof AppIndexRoute;
    "/app/account/membership": typeof AppAccountMembershipRoute;
    "/app/account/notifications": typeof AppAccountNotificationsRoute;
    "/app/account/orders": typeof AppAccountOrdersRoute;
    "/app/account/profile": typeof AppAccountProfileRoute;
    "/app/account/security": typeof AppAccountSecurityRoute;
    "/app/account/sessions": typeof AppAccountSessionsRoute;
    "/app/admin/content": typeof AppAdminContentRoute;
    "/app/admin/licenses": typeof AppAdminLicensesRoute;
    "/app/admin/system": typeof AppAdminSystemRoute;
    "/app/admin/users": typeof AppAdminUsersRoute;
    "/app/content/library": typeof AppContentLibraryRoute;
    "/app/content/packages": typeof AppContentPackagesRouteWithChildren;
    "/app/content/publishing": typeof AppContentPublishingRoute;
    "/app/content/review": typeof AppContentReviewRoute;
    "/app/learning/courses": typeof AppLearningCoursesRoute;
    "/app/learning/progress": typeof AppLearningProgressRoute;
    "/app/settings/general": typeof AppSettingsGeneralRoute;
    "/app/settings/preferences": typeof AppSettingsPreferencesRoute;
    "/app/account/": typeof AppAccountIndexRoute;
    "/app/admin/": typeof AppAdminIndexRoute;
    "/app/content/": typeof AppContentIndexRoute;
    "/app/learning/": typeof AppLearningIndexRoute;
    "/app/settings/": typeof AppSettingsIndexRoute;
    "/app/content/packages/new": typeof AppContentPackagesNewRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | "/"
        | "/app"
        | "/app/dashboard"
        | "/auth/forgot-password"
        | "/auth/login"
        | "/auth/signup"
        | "/app/"
        | "/app/account/membership"
        | "/app/account/notifications"
        | "/app/account/orders"
        | "/app/account/profile"
        | "/app/account/security"
        | "/app/account/sessions"
        | "/app/admin/content"
        | "/app/admin/licenses"
        | "/app/admin/system"
        | "/app/admin/users"
        | "/app/content/library"
        | "/app/content/packages"
        | "/app/content/publishing"
        | "/app/content/review"
        | "/app/learning/courses"
        | "/app/learning/progress"
        | "/app/settings/general"
        | "/app/settings/preferences"
        | "/app/account/"
        | "/app/admin/"
        | "/app/content/"
        | "/app/learning/"
        | "/app/settings/"
        | "/app/content/packages/new";
    fileRoutesByTo: FileRoutesByTo;
    to:
        | "/"
        | "/app/dashboard"
        | "/auth/forgot-password"
        | "/auth/login"
        | "/auth/signup"
        | "/app"
        | "/app/account/membership"
        | "/app/account/notifications"
        | "/app/account/orders"
        | "/app/account/profile"
        | "/app/account/security"
        | "/app/account/sessions"
        | "/app/admin/content"
        | "/app/admin/licenses"
        | "/app/admin/system"
        | "/app/admin/users"
        | "/app/content/library"
        | "/app/content/packages"
        | "/app/content/publishing"
        | "/app/content/review"
        | "/app/learning/courses"
        | "/app/learning/progress"
        | "/app/settings/general"
        | "/app/settings/preferences"
        | "/app/account"
        | "/app/admin"
        | "/app/content"
        | "/app/learning"
        | "/app/settings"
        | "/app/content/packages/new";
    id:
        | "__root__"
        | "/"
        | "/app"
        | "/app/dashboard"
        | "/auth/forgot-password"
        | "/auth/login"
        | "/auth/signup"
        | "/app/"
        | "/app/account/membership"
        | "/app/account/notifications"
        | "/app/account/orders"
        | "/app/account/profile"
        | "/app/account/security"
        | "/app/account/sessions"
        | "/app/admin/content"
        | "/app/admin/licenses"
        | "/app/admin/system"
        | "/app/admin/users"
        | "/app/content/library"
        | "/app/content/packages"
        | "/app/content/publishing"
        | "/app/content/review"
        | "/app/learning/courses"
        | "/app/learning/progress"
        | "/app/settings/general"
        | "/app/settings/preferences"
        | "/app/account/"
        | "/app/admin/"
        | "/app/content/"
        | "/app/learning/"
        | "/app/settings/"
        | "/app/content/packages/new";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    AppRoute: typeof AppRouteWithChildren;
    AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
    AuthLoginRoute: typeof AuthLoginRoute;
    AuthSignupRoute: typeof AuthSignupRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/app": {
            id: "/app";
            path: "/app";
            fullPath: "/app";
            preLoaderRoute: typeof AppRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/app/": {
            id: "/app/";
            path: "/";
            fullPath: "/app/";
            preLoaderRoute: typeof AppIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/dashboard": {
            id: "/app/dashboard";
            path: "/dashboard";
            fullPath: "/app/dashboard";
            preLoaderRoute: typeof AppDashboardRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/auth/forgot-password": {
            id: "/auth/forgot-password";
            path: "/auth/forgot-password";
            fullPath: "/auth/forgot-password";
            preLoaderRoute: typeof AuthForgotPasswordRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/login": {
            id: "/auth/login";
            path: "/auth/login";
            fullPath: "/auth/login";
            preLoaderRoute: typeof AuthLoginRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/auth/signup": {
            id: "/auth/signup";
            path: "/auth/signup";
            fullPath: "/auth/signup";
            preLoaderRoute: typeof AuthSignupRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/app/account/": {
            id: "/app/account/";
            path: "/account";
            fullPath: "/app/account/";
            preLoaderRoute: typeof AppAccountIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/membership": {
            id: "/app/account/membership";
            path: "/account/membership";
            fullPath: "/app/account/membership";
            preLoaderRoute: typeof AppAccountMembershipRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/notifications": {
            id: "/app/account/notifications";
            path: "/account/notifications";
            fullPath: "/app/account/notifications";
            preLoaderRoute: typeof AppAccountNotificationsRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/orders": {
            id: "/app/account/orders";
            path: "/account/orders";
            fullPath: "/app/account/orders";
            preLoaderRoute: typeof AppAccountOrdersRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/profile": {
            id: "/app/account/profile";
            path: "/account/profile";
            fullPath: "/app/account/profile";
            preLoaderRoute: typeof AppAccountProfileRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/security": {
            id: "/app/account/security";
            path: "/account/security";
            fullPath: "/app/account/security";
            preLoaderRoute: typeof AppAccountSecurityRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/account/sessions": {
            id: "/app/account/sessions";
            path: "/account/sessions";
            fullPath: "/app/account/sessions";
            preLoaderRoute: typeof AppAccountSessionsRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/admin/": {
            id: "/app/admin/";
            path: "/admin";
            fullPath: "/app/admin/";
            preLoaderRoute: typeof AppAdminIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/admin/content": {
            id: "/app/admin/content";
            path: "/admin/content";
            fullPath: "/app/admin/content";
            preLoaderRoute: typeof AppAdminContentRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/admin/licenses": {
            id: "/app/admin/licenses";
            path: "/admin/licenses";
            fullPath: "/app/admin/licenses";
            preLoaderRoute: typeof AppAdminLicensesRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/admin/system": {
            id: "/app/admin/system";
            path: "/admin/system";
            fullPath: "/app/admin/system";
            preLoaderRoute: typeof AppAdminSystemRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/admin/users": {
            id: "/app/admin/users";
            path: "/admin/users";
            fullPath: "/app/admin/users";
            preLoaderRoute: typeof AppAdminUsersRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/": {
            id: "/app/content/";
            path: "/content";
            fullPath: "/app/content/";
            preLoaderRoute: typeof AppContentIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/library": {
            id: "/app/content/library";
            path: "/content/library";
            fullPath: "/app/content/library";
            preLoaderRoute: typeof AppContentLibraryRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/packages": {
            id: "/app/content/packages";
            path: "/content/packages";
            fullPath: "/app/content/packages";
            preLoaderRoute: typeof AppContentPackagesRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/publishing": {
            id: "/app/content/publishing";
            path: "/content/publishing";
            fullPath: "/app/content/publishing";
            preLoaderRoute: typeof AppContentPublishingRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/review": {
            id: "/app/content/review";
            path: "/content/review";
            fullPath: "/app/content/review";
            preLoaderRoute: typeof AppContentReviewRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/learning/": {
            id: "/app/learning/";
            path: "/learning";
            fullPath: "/app/learning/";
            preLoaderRoute: typeof AppLearningIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/learning/courses": {
            id: "/app/learning/courses";
            path: "/learning/courses";
            fullPath: "/app/learning/courses";
            preLoaderRoute: typeof AppLearningCoursesRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/learning/progress": {
            id: "/app/learning/progress";
            path: "/learning/progress";
            fullPath: "/app/learning/progress";
            preLoaderRoute: typeof AppLearningProgressRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/settings/": {
            id: "/app/settings/";
            path: "/settings";
            fullPath: "/app/settings/";
            preLoaderRoute: typeof AppSettingsIndexRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/settings/general": {
            id: "/app/settings/general";
            path: "/settings/general";
            fullPath: "/app/settings/general";
            preLoaderRoute: typeof AppSettingsGeneralRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/settings/preferences": {
            id: "/app/settings/preferences";
            path: "/settings/preferences";
            fullPath: "/app/settings/preferences";
            preLoaderRoute: typeof AppSettingsPreferencesRouteImport;
            parentRoute: typeof AppRoute;
        };
        "/app/content/packages/new": {
            id: "/app/content/packages/new";
            path: "/new";
            fullPath: "/app/content/packages/new";
            preLoaderRoute: typeof AppContentPackagesNewRouteImport;
            parentRoute: typeof AppContentPackagesRoute;
        };
    }
}

interface AppContentPackagesRouteChildren {
    AppContentPackagesNewRoute: typeof AppContentPackagesNewRoute;
}

const AppContentPackagesRouteChildren: AppContentPackagesRouteChildren = {
    AppContentPackagesNewRoute: AppContentPackagesNewRoute,
};

const AppContentPackagesRouteWithChildren = AppContentPackagesRoute._addFileChildren(AppContentPackagesRouteChildren);

interface AppRouteChildren {
    AppDashboardRoute: typeof AppDashboardRoute;
    AppIndexRoute: typeof AppIndexRoute;
    AppAccountMembershipRoute: typeof AppAccountMembershipRoute;
    AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute;
    AppAccountOrdersRoute: typeof AppAccountOrdersRoute;
    AppAccountProfileRoute: typeof AppAccountProfileRoute;
    AppAccountSecurityRoute: typeof AppAccountSecurityRoute;
    AppAccountSessionsRoute: typeof AppAccountSessionsRoute;
    AppAdminContentRoute: typeof AppAdminContentRoute;
    AppAdminLicensesRoute: typeof AppAdminLicensesRoute;
    AppAdminSystemRoute: typeof AppAdminSystemRoute;
    AppAdminUsersRoute: typeof AppAdminUsersRoute;
    AppContentLibraryRoute: typeof AppContentLibraryRoute;
    AppContentPackagesRoute: typeof AppContentPackagesRouteWithChildren;
    AppContentPublishingRoute: typeof AppContentPublishingRoute;
    AppContentReviewRoute: typeof AppContentReviewRoute;
    AppLearningCoursesRoute: typeof AppLearningCoursesRoute;
    AppLearningProgressRoute: typeof AppLearningProgressRoute;
    AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute;
    AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute;
    AppAccountIndexRoute: typeof AppAccountIndexRoute;
    AppAdminIndexRoute: typeof AppAdminIndexRoute;
    AppContentIndexRoute: typeof AppContentIndexRoute;
    AppLearningIndexRoute: typeof AppLearningIndexRoute;
    AppSettingsIndexRoute: typeof AppSettingsIndexRoute;
}

const AppRouteChildren: AppRouteChildren = {
    AppDashboardRoute: AppDashboardRoute,
    AppIndexRoute: AppIndexRoute,
    AppAccountMembershipRoute: AppAccountMembershipRoute,
    AppAccountNotificationsRoute: AppAccountNotificationsRoute,
    AppAccountOrdersRoute: AppAccountOrdersRoute,
    AppAccountProfileRoute: AppAccountProfileRoute,
    AppAccountSecurityRoute: AppAccountSecurityRoute,
    AppAccountSessionsRoute: AppAccountSessionsRoute,
    AppAdminContentRoute: AppAdminContentRoute,
    AppAdminLicensesRoute: AppAdminLicensesRoute,
    AppAdminSystemRoute: AppAdminSystemRoute,
    AppAdminUsersRoute: AppAdminUsersRoute,
    AppContentLibraryRoute: AppContentLibraryRoute,
    AppContentPackagesRoute: AppContentPackagesRouteWithChildren,
    AppContentPublishingRoute: AppContentPublishingRoute,
    AppContentReviewRoute: AppContentReviewRoute,
    AppLearningCoursesRoute: AppLearningCoursesRoute,
    AppLearningProgressRoute: AppLearningProgressRoute,
    AppSettingsGeneralRoute: AppSettingsGeneralRoute,
    AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
    AppAccountIndexRoute: AppAccountIndexRoute,
    AppAdminIndexRoute: AppAdminIndexRoute,
    AppContentIndexRoute: AppContentIndexRoute,
    AppLearningIndexRoute: AppLearningIndexRoute,
    AppSettingsIndexRoute: AppSettingsIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AppRoute: AppRouteWithChildren,
    AuthForgotPasswordRoute: AuthForgotPasswordRoute,
    AuthLoginRoute: AuthLoginRoute,
    AuthSignupRoute: AuthSignupRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
